language: cpp

compiler:
  - gcc
#  - clang

before_install:
 - sudo apt-get update -qq
 - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.2.tar.gz
 - tar xf cmake-2.8.12.2.tar.gz
 - cd cmake-2.8.12.2

install:
 - sudo apt-get install -qq libboost-all-dev libcurl3-dev
 - ./bootstrap --system-curl
 - make
 - sudo make install
 - cd ..

before_script:
  - mkdir build.ci
  - cd build.ci
  - cmake ..

script: make

branches:
  only:
    - develop

notifications:
  recipients:
    - sergey.nikulov@gmail.com
  email:
    on_success: change
    on_failure: always
